Repository Dong-kyu-Lee/ProjectR, pull requests merged in 2025-05, with the labels that each got.

#107 Feature/AdjustBartenderResource2
  Assets/Resources/Bartender/Bartender.controller
Labels: bug

#110 Feature/UpgradeStatus2
  Assets/MeleeEnemyData 1.asset
  Assets/Resources/Prefabs/BartenderExplode.prefab
  Assets/Resources/Prefabs/BartenderExplode.prefab.meta
  Assets/Resources/Prefabs/BartenderProjectile.prefab
  Assets/Resources/Prefabs/UpgradeUICanvas 1.0.prefab
  Assets/Scenes/Lobby + UpgradeScene.unity
  Assets/Scripts/BartenderAbility.cs
  Assets/Scripts/BartenderController.cs
  Assets/Scripts/BuffScripts/Buff.cs
  Assets/Scripts/BuffScripts/BuffFactory.cs
  Assets/Scripts/BuffScripts/BuffManager.cs
  Assets/Scripts/BuffScripts/BuffTypes.cs
  Assets/Scripts/BuffScripts/ConcreteBuffs/Debuffs/BurnDeBuff.cs
  Assets/Scripts/BuffScripts/ConcreteBuffs/Debuffs/BurnDeBuff.cs.meta
  Assets/Scripts/BuffScripts/ConcreteBuffs/Debuffs/BuzzedDeBuff.cs
  Assets/Scripts/BuffScripts/ConcreteBuffs/Debuffs/BuzzedDeBuff.cs.meta
  Assets/Scripts/BuffScripts/ConcreteBuffs/Debuffs/DrunkenDeBuff.cs
  Assets/Scripts/BuffScripts/ConcreteBuffs/Debuffs/FreezeDeBuff.cs
  Assets/Scripts/BuffScripts/ConcreteBuffs/Debuffs/PoisonDeBuff.cs
  Assets/Scripts/Enemy/ChaseState.cs
  Assets/Scripts/Enemy/Enemy.cs
  Assets/Scripts/Enemy/EnemyStatus.cs
  Assets/Scripts/Enemy/HitBox.cs
  Assets/Scripts/Fight/CalcReceiveDamage.cs
  Assets/Scripts/ItemScripts/ToolTypeItem/DynamiteProjectile.cs
  Assets/Scripts/Liberation/AbilityManager.cs
  Assets/Scripts/Liberation/AbilityManager.cs.meta
  Assets/Scripts/Liberation/BartenderLiberation.cs
  Assets/Scripts/Liberation/BartenderLiberation.cs.meta
  Assets/Scripts/Liberation/LiberationDesc.cs
  Assets/Scripts/Liberation/LiberationSystem.cs
  Assets/Scripts/ObjectPoolManager.cs
  Assets/Scripts/PlayerStatus.cs
  Assets/Scripts/Projectile.cs
  Assets/Scripts/Status.cs
  Assets/Scripts/StatusUpgrade/LevelUp.cs
  Assets/Scripts/StatusUpgrade/UpgradeOnClick.cs
  Assets/Scripts/StatusUpgrade/UpgradeSystem.cs
  ProjectSettings/Physics2DSettings.asset
Labels: feature

#111 Feature/UpgradeStatus2
  Assets/MeleeEnemyData 1.asset
  Assets/MeleeEnemyData.asset
  Assets/New Universal Render Pipeline Asset_Renderer.asset
  Assets/Resources/Prefabs/BartenderProjectile.prefab
  Assets/Resources/Prefabs/MeleeEnemy1_1.prefab
  Assets/Resources/Prefabs/Player1_2.prefab
  Assets/Scenes/Lobby + UpgradeScene.unity
  Assets/Scripts/Enemy/EnemyData.cs
  Assets/Scripts/Enemy/EnemyStatus.cs
  Assets/Scripts/Projectile.cs
  Assets/Scripts/StatusUpgrade/LevelUp.cs
Labels: bug, feature

#112 Feature/ingame UI
  Assets/Resources/BuffImage/공속.png
  Assets/Resources/BuffImage/공속.png.meta
  Assets/Resources/BuffImage/공속2.png
  Assets/Resources/BuffImage/공속2.png.meta
  Assets/Resources/BuffImage/만취.png
  Assets/Resources/BuffImage/만취.png.meta
  Assets/Resources/BuffImage/매의 눈.png
  Assets/Resources/BuffImage/매의 눈.png.meta
  Assets/Resources/BuffImage/무적.png
  Assets/Resources/BuffImage/무적.png.meta
  Assets/Resources/BuffImage/반사.png
  Assets/Resources/BuffImage/반사.png.meta
  Assets/Resources/BuffImage/스턴.png
  Assets/Resources/BuffImage/스턴.png.meta
  Assets/Resources/Prefabs/Buff,Debuff/Buff.prefab
  Assets/Resources/Prefabs/Buff,Debuff/BuffToolTip.prefab
  Assets/Resources/Prefabs/Canvas(QuickSlot).prefab
  Assets/Resources/Prefabs/Player(Buff).prefab
  Assets/Resources/Prefabs/Player(Buff.prefab
  Assets/Resources/Prefabs/Player(Buff.prefab.meta
  Assets/Scenes/InGameUI Scene.unity
  Assets/Scenes/InventoryUIScene.unity
  Assets/Scripts/BuffScripts/Buff.cs
  Assets/Scripts/BuffScripts/BuffManager.cs
  Assets/Scripts/BuffScripts/BuffUIManager.cs
  Assets/Scripts/BuffScripts/ConcreteBuffs/Debuffs/BleedingDebuff.cs
  Assets/Scripts/BuffScripts/ConcreteBuffs/Debuffs/ConfusionDeBuff.cs
  Assets/Scripts/BuffScripts/ConcreteBuffs/Debuffs/SleepDeBuff.cs
  Assets/Scripts/BuffScripts/ConcreteBuffs/Debuffs/SlowDeBuff.cs
  Assets/Scripts/BuffScripts/ConcreteBuffs/Debuffs/StoneCurseDeBuff.cs
  Assets/Scripts/BuffScripts/ConcreteBuffs/Debuffs/StunDeBuff.cs
  Assets/Scripts/BuffScripts/ConcreteBuffs/ReflectionBuff.cs
  Assets/Scripts/BuffScripts/ConcreteBuffs/UpgradeBuff/Critical4Buff.cs
  Assets/Scripts/BuffScripts/ConcreteBuffs/UpgradeBuff/Critical7Buff.cs
  Assets/Scripts/BuffScripts/ConcreteBuffs/UpgradeBuff/Dexterity13Buff.cs
  Assets/Scripts/BuffScripts/ConcreteBuffs/UpgradeBuff/Dexterity7Buff.cs
  Assets/Scripts/BuffScripts/ConcreteBuffs/UpgradeBuff/Force16Buff.cs
  Assets/Scripts/BuffScripts/ConcreteBuffs/UpgradeBuff/Force7Buff.cs
  Assets/Scripts/CharacterInfo.cs
  Assets/Scripts/InGameUI/BuffIconUI.cs
  Assets/Scripts/InGameUI/BuffToolTipUI.cs
  Assets/Scripts/InGameUI/BuffToolTipUI.cs.meta
  Assets/Scripts/InGameUI/InGameUIManager.cs
Labels: bug, enhancement, feature

#115 Feature/ingame UI
  Assets/Resources/Prefabs/InGameUICanvas.prefab
  Assets/Resources/Prefabs/InGameUICanvas.prefab.meta
  Assets/Resources/Prefabs/Player1_2.prefab
  Assets/Scenes/InGameUI Scene.unity
  Assets/Scenes/LobbyScene 1.unity
  Assets/Scenes/LobbyScene.unity
  Assets/Scenes/itemDropBoxScene.unity
  Assets/Scripts/BuffScripts/ConcreteBuffs/Debuffs/BleedingDebuff.cs
  Assets/Scripts/CharacterInfo.cs
  Assets/Scripts/Enemy/HitBox.cs
  Assets/Scripts/GameManager.cs
  Assets/Scripts/InGameUI/InGameUIManager.cs
  Assets/Scripts/ItemScripts/Inventory.cs
  Assets/Scripts/Status.cs
  Assets/Scripts/UIScripts/InventoryUI.cs
  Assets/Scripts/UIScripts/ItemSlotUI.cs
Labels: bug, feature
