Repository Dong-kyu-Lee/ProjectR, pull requests merged in 2025-07, with the labels that each got.

#122 Feature/EnemyEdgeDetection
  Assets/Resources/Prefabs/MeleeEnemy1_2.prefab
  Assets/Resources/Prefabs/MeleeEnemy1_2.prefab.meta
  Assets/Scenes/PlayerRefactoringTestScene.unity
  Assets/Scripts/Enemy/ChaseState.cs
  Assets/Scripts/Enemy/Enemy.cs
  Assets/Scripts/Enemy/WanderState.cs
Labels: enhancement, feature

#131 Feature/RangedEnemy
  Assets/RangedEnemyData.asset
  Assets/RangedEnemyData.asset.meta
  Assets/Resources/Prefabs/Bartender2_1.prefab
  Assets/Resources/Prefabs/Blacksmith2_1.prefab
  Assets/Resources/Prefabs/RangedEnemy1_1.prefab
  Assets/Resources/Prefabs/RangedEnemy1_1.prefab.meta
  Assets/Resources/Prefabs/RangedEnemyProjectile.prefab
  Assets/Resources/Prefabs/RangedEnemyProjectile.prefab.meta
  Assets/Scenes/PlayerRefactoringTestScene.unity
  Assets/Scripts/Enemy/RangedEnemy.cs
  Assets/Scripts/Enemy/RangedEnemy.cs.meta
  Assets/Scripts/Enemy/RangedEnemyProjectile.cs
  Assets/Scripts/Enemy/RangedEnemyProjectile.cs.meta
  Assets/Scripts/Enemy/StateMachine.meta
  Assets/Scripts/Enemy/StateMachine/AttackState.cs
  Assets/Scripts/Enemy/StateMachine/AttackState.cs.meta
  Assets/Scripts/Enemy/StateMachine/ChaseState.cs
  Assets/Scripts/Enemy/StateMachine/ChaseState.cs.meta
  Assets/Scripts/Enemy/StateMachine/DeadState.cs
  Assets/Scripts/Enemy/StateMachine/DeadState.cs.meta
  Assets/Scripts/Enemy/StateMachine/EnemyAIController.cs
  Assets/Scripts/Enemy/StateMachine/EnemyAIController.cs.meta
  Assets/Scripts/Enemy/StateMachine/IState.cs
  Assets/Scripts/Enemy/StateMachine/IState.cs.meta
  Assets/Scripts/Enemy/StateMachine/IdleState.cs
  Assets/Scripts/Enemy/StateMachine/IdleState.cs.meta
  Assets/Scripts/Enemy/StateMachine/MeleeAttackState.cs
  Assets/Scripts/Enemy/StateMachine/MeleeAttackState.cs.meta
  Assets/Scripts/Enemy/StateMachine/RangedAttackState.cs
  Assets/Scripts/Enemy/StateMachine/RangedAttackState.cs.meta
  Assets/Scripts/Enemy/StateMachine/WanderState.cs
  Assets/Scripts/Enemy/StateMachine/WanderState.cs.meta
  ProjectSettings/Physics2DSettings.asset
  ProjectSettings/TagManager.asset
Labels: enhancement, feature

#144 Feature/dungeon generate
  Assets/Resources/Prefabs/Bartender2_1 Variant.prefab
  Assets/Resources/Prefabs/Bartender2_1 Variant.prefab.meta
  Assets/Resources/Prefabs/Map Prefabs/RoomPrefab.prefab
  Assets/Scenes/DungeonGenerate.unity
  Assets/Scenes/LobbyScene.unity
  Assets/Scenes/ShopScene.unity
  Assets/Scenes/TempFinalBoss.unity
  Assets/Scenes/TempFinalBoss.unity.meta
  Assets/Scripts/Camera.meta
  Assets/Scripts/Camera/CM_DungeonScene.cs
  Assets/Scripts/Camera/CM_DungeonScene.cs.meta
  Assets/Scripts/Camera/CM_LobbyScene.cs
  Assets/Scripts/Camera/CM_LobbyScene.cs.meta
  Assets/Scripts/CharacterSelect/CharacterSelect.cs
  Assets/Scripts/DungeonScripts/DungeonCreator.cs
  Assets/Scripts/DungeonScripts/DungeonFlowManager.cs
  Assets/Scripts/DungeonScripts/RoomInstance.cs
  Assets/Scripts/DungeonScripts/ShopSceneManager.cs
  Assets/Scripts/DungeonScripts/ShopSceneManager.cs.meta
  Assets/Scripts/DungeonScripts/Stage.cs
  Packages/manifest.json
  Packages/packages-lock.json
  ProjectSettings/EditorBuildSettings.asset
Labels: feature

#145 Feature/UpgradeStatus2
  Assets/MeleeEnemyData.asset
  Assets/Scenes/UpgradeTestScene.unity
  Assets/Scenes/UpgradeTestScene.unity.meta
  Assets/Scripts/BuffScripts/ConcreteBuffs/UpgradeBuff/Critical4Buff.cs
  Assets/Scripts/DungeonScripts/FinishSpot.cs
  Assets/Scripts/Fight/CalcDamage.cs
  Assets/Scripts/Fight/CalcReceiveDamage.cs
  Assets/Scripts/Player/V2/PlayerControllerBase.cs
Labels: bug
